version: '1'
services:
  redis:
    image: "redis:3.0.7"
  postgres:
    image: "postgres:latest"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    web:
      build: .
      ports:
        - "80:3000"
      volumes:
        - .:/usr/src/app
      depends_on:
        - postgres
        - redis
      command: ["./wait_for_it.sh", "postgres:5432", "--", "npm", "start"]
      
